namespace UltimateMods.Localization;

public enum TransKey
{
    Translator,
    Language,
    LanguageName,
    ModOptionsText,
    VanillaOptionsText,
    GeneralSettings,
    CrewmateSettings,
    ImpostorSettings,
    NeutralSettings,
    ModifierSettings,
    OtherSettings,
    OptionOn,
    OptionOff,
    FormatVotes,
    FormatSeconds,
    FormatTimes,
    FormatPlayer,
    FormatShots,
    FormatPercent,
    FormatMultiplier,
    Preset1,
    Preset2,
    Preset3,
    Preset4,
    Preset5,

    CrewmateWin,
    ImpostorWin,
    JesterWin,
    TeamJackalWin,
    ArsonistWin,
    ForceEnd,
    EveryoneLose,
    CrewWinExtra,
    ImpostorWinExtra,
    JesterWinExtra,
    TeamJackalWinExtra,
    ArsonistWinExtra,
    ReactorWin,
    O2Win,
    TaskWin,
    OpportunistExtra,
    FinishedByHost,

    RoleSummaryText,
    RoleSummaryAlive,
    RoleSummarySabotage,
    RoleSummaryReactor,
    RoleSummaryExiled,
    RoleSummaryMisfire,
    RoleSummarySuicide,
    RoleSummaryDead,
    RoleSummaryLackO2,
    RoleSummaryBomb,
    RoleSummaryDisconnected,
    RoleSummaryRevival,
    RoleSummaryTorched,

    CreditsMain,
    CreditsVersion,
    CreditsBetaVersion,
    DevName,
    CreditsTitle,

    NoUpdate,
    Updating,
    UpdateManually,
    UpdateInProgress,
    UpdateButton,
    UpdateRestart,
    UpdateFailed,

    Position,
    ErrorNotInstalled,
    ErrorOlderVersion,
    ErrorNewerVersion,
    ErrorWrongVersion,
    ErrorHostNoVersion,

    GhostsSeeTasksButton,
    GhostsSeeVotesButton,
    GhostsSeeRolesButton,
    HideNameplates,
    EnableCustomSounds,
    ShowRoleSummaryButton,

    PlatformTitle,
    MeetingStatus,
    JesterMeetingButton,
    RestrictOutOfTime,
    TimeRemaining,
    ButtonBlocked,
    ExilePlayer,

    ReamingShots,
    ReamingCount,
    MakeBreadText,
    BombBakeryText,
    TeleporterTeleported,
    JackalWithSidekick,

    Impostor,
    Crewmate,
    Jester,
    Sheriff,
    Engineer,
    CustomImpostor,
    UnderTaker,
    BountyHunter,
    Madmate,
    Bakery,
    Teleporter,
    Altruist,
    Snitch,
    Jackal,
    Sidekick,
    EvilHacker,
    Adversity,
    Seer,
    Arsonist,
    Lighter,
    Yakuza,
    Mayor,

    ImpostorIntro,
    ImpostorShort,
    ImpostorFull,

    CrewmateIntro,
    CrewmateShort,
    CrewmateFull,

    JesterIntro,
    JesterShort,
    JesterFull,

    SheriffIntro,
    SheriffShort,
    SheriffFull,

    EngineerIntro,
    EngineerShort,
    EngineerFull,

    CustomImpostorIntro,
    CustomImpostorShort,
    CustomImpostorFull,

    UnderTakerIntro,
    UnderTakerShort,
    UnderTakerFull,

    MadmateIntro,
    MadmateShort,
    MadmateFull,

    BakeryIntro,
    BakeryShort,
    BakeryFull,

    BountyHunterIntro,
    BountyHunterShort,
    BountyHunterFull,

    TeleporterIntro,
    TeleporterShort,
    TeleporterFull,

    AltruistIntro,
    AltruistShort,
    AltruistFull,

    SnitchIntro,
    SnitchShort,
    SnitchFull,

    JackalIntro,
    JackalShort,
    JackalFull,

    SidekickShort,
    SidekickFull,

    EvilHackerIntro,
    EvilHackerShort,
    EvilHackerFull,

    AdversityIntro,
    AdversityShort,
    AdversityFull,

    SeerIntro,
    SeerShort,
    SeerFull,

    ArsonistIntro,
    ArsonistShort,
    ArsonistFull,

    LighterIntro,
    LighterShort,
    LighterFull,

    MayorIntro,
    MayorShort,
    MayorFull,

    Opportunist,
    Sanglasses,
    Watcher,

    OPIntro,
    WTIntro,
    SGIntro,

    ChangePage,
    BlockSkip,
    ActivateRoles,
    PresetSelection,
    RandomGen,
    CrewmateRoles,
    NeutralRoles,
    ImpostorRoles,
    ModifierRoles,
    CrewmateRolesCount,
    NeutralRolesCount,
    ImpostorRolesCount,
    ModifierCount,
    MaxNumberOfMeetings,
    NoVoteIsSelfVote,
    NoMedBayLimit,
    HideOutName,
    HidePlayerName,
    RefundVoteDeath,
    MirrorMap,
    CanZoomInOutDead,
    PlayRandomMaps,
    RandomMapsEnableSkeld,
    RandomMapsEnableMira,
    RandomMapsEnablePolus,
    RandomMapsEnableAirShip,
    RestrictDevices,
    DisableAdmin,
    DisableCameras,
    DisableVitals,
    RestrictPerTurn,
    RestrictPerGame,
    AirShipSettings,
    OldAirShipAdmin,
    EnableRecordsAdmin,
    EnableCockpitAdmin,
    AirShipReactorDuration,
    EnableCustomTasks,

    RoleNumAssigned,
    CanSabotage,
    MaxShots,
    CanKillNeutral,
    KillCooldowns,
    MisfireKillsTarget,
    CanUseVents,
    CanEmergencyMeeting,
    HasImpostorVision,
    CanDieToSheriff,
    CanFixO2,
    CanFixComms,
    CanFixReactor,
    CanFixBlackout,
    HasTasks,
    NumCommonTasks,
    NumLongTasks,
    NumShortTasks,

    CanMoveInVents,

    JesterMustFinishTasks,

    EngineerCanFixSabo,
    EngineerSaboFixCount,

    UnderTakerButtonCooldown,
    UnderTakerHasDuration,
    UnderTakerDuration,
    UnderTakerDraggingSpeed,
    UnderTakerCanDumpDeadBodyInVent,

    BountyHunterSuccess,
    BountyHunterMiss,
    BountyHunterDuration,
    BountyHunterShowArrow,
    BountyHunterArrowUpdateCooldown,

    MadmateKnowImpostorTaskEnd,
    MadmateCanWinWhenTaskEnd,

    BakeryBombRate,

    TeleporterButtonCooldown,
    TeleporterTeleportTo,
    TeleporterAllRandom,
    OnlyCrewmate,

    AltruistDuration,

    EvilHackerCanHasBetterAdmin,

    AdversityStateKillCooldown,
    AdversityStateCanFindMadmate,
    AdversityStateCanSeeVotes,

    JackalCanUseVents,
    JackalAndSidekickHaveImpostorVision,
    JackalCanCreateSidekick,
    JackalCreateSidekickCooldown,
    SidekickPromotesToJackal,
    SidekickCanKill,
    SidekickCanUseVents,
    JackalPromotedFromSidekickCanCreateSidekick,

    SeerMode,
    SeerLimitSoulDuration,
    SeerSoulDuration,
    SeerModeBoth,
    SeerModeFlash,
    SeerModeSouls,

    ArsonistCooldown,
    ArsonistDuration,

    SnitchLeftTasksForReveal,
    SnitchIncludeTeamJackal,

    LighterCooldowns,
    LighterDurations,
    LighterModeLightsOnVision,
    LighterModeLightsOffVision,

    SunglassesEye,

    MayorNumVotes,
    MayorMeetingButton,
    MayorNumMeetingButton,

    EngineerRepairButtonText,
    UnderTakerDropText,
    UnderTakerDragText,
    TeleportButtonText,
    AltruistReviveText,
    JackalSidekickText,
    IgniteText,
    DouseText,
    LighterText,
    MayorMeetingButtonText,
}